### ISSUE TITLE
sphinx-issues feedstock unmaintained?

### ISSUE THREAD

**Issue by bjlittle** [conda-forge/sphinx-issues-feedstock#14]
### Comment:

Hi @asmeurer!

It's been a while since this feedstock was updated to sync it with the [sphinx-issues](https://github.com/sloria/sphinx-issues) repo, which is now on 4.1.0.

If you're not active or don't have the time, then I'm more than happy to help out and maintain the feedstock to keep it uptodate for the community.

I'm really keen to use `sphinx-issues` but would prefer to use `conda` over `pip` with a modern version.

Many thanks 😄

**Comment by m-rossi** [comment]
We just updated in #15

**Comment by asmeurer** [comment]
Sorry, I tend to ignore most feedstock notifications since I'm on a lot of them, and I didn't realize I was the only maintainer for this one. It might be a good idea to add automerge for the bot updates to this repo, since it's just a simple Python package.

**Comment by m-rossi** [comment]
@asmeurer No worries. Thanks for maintenance of the feedstock. @zaneselvans & me are now here to help in the future.

**Comment by zaneselvans** [comment]
I've added automerge and will keep an eye on it for the next update!
